{% set name = "atool2" %}
{% set version = "0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/solsticedhiver/atool2/archive/{{ version }}.tar.gz
  sha256: 87fc55cc21e2ac74c356797fc4e1d73b37dd37a6b91811cea778c68787079239

build:
  # Missing automake
  skip: true  # [win]
  number: 0
  # noarch: generic # Re-enable after fixing Windows build
  script:
    - ln -fs $BUILD_PREFIX/share/automake-*/install-sh build-aux/install-sh
    - ./configure --prefix=$PREFIX
    - head atool
    - sed -i"" -e "1s@perl -w@/usr/bin/env $PREFIX/bin/perl@g" atool  # See https://github.com/conda-forge/atool-feedstock/pull/3
    - head atool
    - make install

requirements:
  build:
    - automake
    - make
    - perl >=5.004
  run:
    - perl >=5.004

test:
  commands:
    - atool --help
    - aunpack --help
    - apack --help

about:
  home: https://github.com/solsticedhiver/atool2
  summary: atool with support for zstd
  description: |
    atool is a script for managing file archives of various types (tar, tar+gzip, zip etc).
  license: GPL-3.0-only
  license_file: COPYING

extra:
  recipe-maintainers:
    - jonashaag
